# Generated by Django 6.0.3 on 2026-03-27 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('uri', models.URLField()),
                ('has_members', models.ManyToManyField(blank=True, related_name='domian_members', to=settings.AUTH_USER_MODEL, verbose_name='domian_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_owner', to=settings.AUTH_USER_MODEL, verbose_name='domain_owner')),
            ],
            options={
                'abstract': False,
                'unique_together': {('uri', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('uri', models.URLField(blank=True, help_text='The URI of the instance.', null=True)),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.domain')),
                ('has_members', models.ManyToManyField(blank=True, related_name='object_members', to=settings.AUTH_USER_MODEL, verbose_name='object_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_owner', to=settings.AUTH_USER_MODEL, verbose_name='object_owner')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('uri', models.URLField(blank=True, help_text='The URI of the instance.', null=True)),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.domain')),
                ('has_members', models.ManyToManyField(blank=True, related_name='predicate_members', to=settings.AUTH_USER_MODEL, verbose_name='predicate_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicate_owner', to=settings.AUTH_USER_MODEL, verbose_name='predicate_owner')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('uri', models.URLField(blank=True, help_text='The URI of the instance.', null=True)),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.domain')),
                ('has_members', models.ManyToManyField(blank=True, related_name='subject_members', to=settings.AUTH_USER_MODEL, verbose_name='subject_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_owner', to=settings.AUTH_USER_MODEL, verbose_name='subject_owner')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('uri', models.URLField(blank=True, help_text='The URI of the instance.', null=True)),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.domain')),
                ('has_members', models.ManyToManyField(blank=True, related_name='tripple_members', to=settings.AUTH_USER_MODEL, verbose_name='tripple_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripple_owner', to=settings.AUTH_USER_MODEL, verbose_name='tripple_owner')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='ontology.object', verbose_name='Object')),
                ('pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicate', to='ontology.predicate', verbose_name='Predicate')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='ontology.subject', verbose_name='Subject')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the instance.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description of the instance.', null=True)),
                ('namespace', models.CharField(blank=True, help_text='The namespace of the instance.', max_length=255, null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the instance.', max_length=255, null=True)),
                ('tag', models.CharField(blank=True, help_text='The tag of the instance.', max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the instance is public.')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the instance is private.')),
                ('uri', models.URLField(blank=True, help_text='The URI of the instance.', null=True)),
                ('api', models.URLField(blank=True, help_text='The REST API of the instance.', null=True)),
                ('wiki', models.URLField(blank=True, help_text='The wiki of the instance.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='The meta data in json format.', null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontology.domain')),
                ('has_members', models.ManyToManyField(blank=True, related_name='graph_members', to=settings.AUTH_USER_MODEL, verbose_name='graph_members')),
                ('has_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_owner', to=settings.AUTH_USER_MODEL, verbose_name='graph_owner')),
                ('tripples', models.ManyToManyField(blank=True, to='ontology.triple')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'name', 'namespace', 'tag', 'has_owner')},
            },
        ),
    ]
